# NumPy (Numerical Python)

In [ ]:
import numpy as np

In [ ]:
## numpy array
nums = [1,20,25,30,100]
arr_nums = np.array(nums)
arr_nums

array([  1,  20,  25,  30, 100])

In [ ]:
print(
    np.sum(arr_nums),
    np.mean(arr_nums),
    np.median(arr_nums),
    np.min(arr_nums),
    np.max(arr_nums),
    np.std(arr_nums),
)

176 35.2 25.0 1 100 33.85498486190771


In [ ]:
print(arr_nums.sum())
print(arr_nums.mean())
print(arr_nums.min())
print(arr_nums.max())
print(arr_nums.std())

176
35.2
1
100
33.85498486190771


In [ ]:
m1 = np.array([
    [1,2],
    [3,4]
])
m1

array([[1, 2],
       [3, 4]])

In [ ]:
# Broadcasting
m1 + 100

array([[101, 102],
       [103, 104]])

In [ ]:
# element wise computation
m1 + m1

array([[2, 4],
       [6, 8]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(1,101,1)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
np.linspace(1, 101, 5)

array([  1.,  26.,  51.,  76., 101.])

In [ ]:
## matrix dot notation
m1 = np.array([
    [1,2],
    [3,4]
])

m2 = np.array([
    [5,5],
    [3,2]
])

In [ ]:
np.dot(m1, m2)

array([[11,  9],
       [27, 23]])

In [ ]:
np.dot(m2, m1)

array([[20, 30],
       [ 9, 14]])

# Pandas

In [ ]:
import pandas as pd

In [ ]:
## create dataframe from scratch
data = {
    "id": [1,2,3],
    "name": ["toy", "anna", "jessica"],
    "city": ["BKK", "JPN", "LON"]
}

df = pd.DataFrame(data)

In [ ]:
df

id     name city
0   1      toy  BKK
1   2     anna  JPN
2   3  jessica  LON

In [ ]:
# add a new column
df["age"] = [35,28,29]
df

id     name city  age
0   1      toy  BKK   35
1   2     anna  JPN   28
2   3  jessica  LON   29

In [ ]:
df.drop("age", axis="columns")

id     name city
0   1      toy  BKK
1   2     anna  JPN
2   3  jessica  LON

In [ ]:
# read csv file from pandas
df = pd.read_csv("data/store.csv")
df

Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2016-152156  2016-11-08  2016-11-11    Second Class   
1          2  CA-2016-152156  2016-11-08  2016-11-11    Second Class   
2          3  CA-2016-138688  2016-06-12  2016-06-16    Second Class   
3          4  US-2015-108966  2015-10-11  2015-10-18  Standard Class   
4          5  US-2015-108966  2015-10-11  2015-10-18  Standard Class   
...      ...             ...         ...         ...             ...   
9989    9990  CA-2014-110422  2014-01-21  2014-01-23    Second Class   
9990    9991  CA-2017-121258  2017-02-26  2017-03-03  Standard Class   
9991    9992  CA-2017-121258  2017-02-26  2017-03-03  Standard Class   
9992    9993  CA-2017-121258  2017-02-26  2017-03-03  Standard Class   
9993    9994  CA-2017-119914  2017-05-04  2017-05-09    Second Class   

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson   
1       CG-12520       Claire Gute   Consumer  United States        Henderson   
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles   
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale   
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale   
...          ...               ...        ...            ...              ...   
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami   
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa   
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa   
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa   
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster   

      ... Postal Code  Region       Product ID         Category Sub-Category  \
0     ...       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1     ...       42420   South  FUR-CH-10000454        Furniture       Chairs   
2     ...       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3     ...       33311   South  FUR-TA-10000577        Furniture       Tables   
4     ...       33311   South  OFF-ST-10000760  Office Supplies      Storage   
...   ...         ...     ...              ...              ...          ...   
9989  ...       33180   South  FUR-FU-10001889        Furniture  Furnishings   
9990  ...       92627    West  FUR-FU-10000747        Furniture  Furnishings   
9991  ...       92627    West  TEC-PH-10003645       Technology       Phones   
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper   
9993  ...       92683    West  OFF-AP-10002684  Office Supplies   Appliances   

                                           Product Name     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2   
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2     Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                        Eldon Fold 'N Roll Cart System   22.3680         2   
...                                                 ...       ...       ...   
9989                             Ultra Door Pull Handle   25.2480         3   
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2   
9991                              Aastra 57i VoIP phone  258.5760         2   
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4   
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2   

      Discount    Profit  
0         0.00   41.9136  
1         0.00  219.5820  
2         0.00    6.8714  
3         0.45 -383.0310  
4         0.20    2.5164  
...        ...       ...  
9989      0.20    4.1028  
9990      0.00   15.6332  
9991      0.20 

In [ ]:
df.head()

Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520   
1       2  CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520   
2       3  CA-2016-138688  2016-06-12  2016-06-16    Second Class    DV-13045   
3       4  US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335   
4       5  US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335   

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1       42420   South  FUR-CH-10000454        Furniture       Chairs   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3       33311   South  FUR-TA-10000577        Furniture       Tables   
4       33311   South  OFF-ST-10000760  Office Supplies      Storage   

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                     Eldon Fold 'N Roll Cart System   22.3680         2   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

In [ ]:
df.tail()

Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
9989    9990  CA-2014-110422  2014-01-21  2014-01-23    Second Class   
9990    9991  CA-2017-121258  2017-02-26  2017-03-03  Standard Class   
9991    9992  CA-2017-121258  2017-02-26  2017-03-03  Standard Class   
9992    9993  CA-2017-121258  2017-02-26  2017-03-03  Standard Class   
9993    9994  CA-2017-119914  2017-05-04  2017-05-09    Second Class   

     Customer ID     Customer Name   Segment        Country         City  ...  \
9989    TB-21400  Tom Boeckenhauer  Consumer  United States        Miami  ...   
9990    DB-13060       Dave Brooks  Consumer  United States   Costa Mesa  ...   
9991    DB-13060       Dave Brooks  Consumer  United States   Costa Mesa  ...   
9992    DB-13060       Dave Brooks  Consumer  United States   Costa Mesa  ...   
9993    CC-12220      Chris Cortes  Consumer  United States  Westminster  ...   

     Postal Code  Region       Product ID         Category Sub-Category  \
9989       33180   South  FUR-FU-10001889        Furniture  Furnishings   
9990       92627    West  FUR-FU-10000747        Furniture  Furnishings   
9991       92627    West  TEC-PH-10003645       Technology       Phones   
9992       92627    West  OFF-PA-10004041  Office Supplies        Paper   
9993       92683    West  OFF-AP-10002684  Office Supplies   Appliances   

                                           Product Name    Sales  Quantity  \
9989                             Ultra Door Pull Handle   25.248         3   
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.960         2   
9991                              Aastra 57i VoIP phone  258.576         2   
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.600         4   
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.160         2   

      Discount   Profit  
9989       0.2   4.1028  
9990       0.0  15.6332  
9991       0.2  19.3932  
9992       0.0  13.3200  
9993       0.0  72.9480  

[5 rows x 21 columns]

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
df.shape

(9994, 21)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Row ID         9994 non-null   int64  
 1   Order ID       9994 non-null   object 
 2   Order Date     9994 non-null   object 
 3   Ship Date      9994 non-null   object 
 4   Ship Mode      9994 non-null   object 
 5   Customer ID    9994 non-null   object 
 6   Customer Name  9994 non-null   object 
 7   Segment        9994 non-null   object 
 8   Country        9994 non-null   object 
 9   City           9994 non-null   object 
 10  State          9994 non-null   object 
 11  Postal Code    9994 non-null   int64  
 12  Region         9994 non-null   object 
 13  Product ID     9994 non-null   object 
 14  Category       9994 non-null   object 
 15  Sub-Category   9994 non-null   object 
 16  Product Name   9994 non-null   object 
 17  Sales          9994 non-null   float64
 18  Quantity

In [ ]:
# clean dataframe column names
col_names = list(df.columns)
clean_col_names = [name.lower().replace(" ", "_").replace("-", "_")
                   for name in col_names]

# assign clean column names to dataframe
df.columns = clean_col_names
df.head()

row_id        order_id  order_date   ship_date       ship_mode customer_id  \
0       1  CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520   
1       2  CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520   
2       3  CA-2016-138688  2016-06-12  2016-06-16    Second Class    DV-13045   
3       4  US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335   
4       5  US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335   

     customer_name    segment        country             city  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  postal_code  region       product_id         category sub_category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1       42420   South  FUR-CH-10000454        Furniture       Chairs   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3       33311   South  FUR-TA-10000577        Furniture       Tables   
4       33311   South  OFF-ST-10000760  Office Supplies      Storage   

                                        product_name     sales  quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                     Eldon Fold 'N Roll Cart System   22.3680         2   

   discount    profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

In [ ]:
## data transformation
df[["customer_id", "customer_name"]].head(3)

customer_id    customer_name
0    CG-12520      Claire Gute
1    CG-12520      Claire Gute
2    DV-13045  Darrin Van Huff

In [ ]:
df[ df["customer_name"] == "Claire Gute" ].head()

row_id        order_id  order_date   ship_date     ship_mode  \
0          1  CA-2016-152156  2016-11-08  2016-11-11  Second Class   
1          2  CA-2016-152156  2016-11-08  2016-11-11  Second Class   
5491    5492  CA-2017-164098  2017-01-26  2017-01-27   First Class   
6877    6878  US-2015-123918  2015-10-15  2015-10-15      Same Day   
6878    6879  US-2015-123918  2015-10-15  2015-10-15      Same Day   

     customer_id customer_name   segment        country       city  ...  \
0       CG-12520   Claire Gute  Consumer  United States  Henderson  ...   
1       CG-12520   Claire Gute  Consumer  United States  Henderson  ...   
5491    CG-12520   Claire Gute  Consumer  United States    Houston  ...   
6877    CG-12520   Claire Gute  Consumer  United States     Dallas  ...   
6878    CG-12520   Claire Gute  Consumer  United States     Dallas  ...   

     postal_code   region       product_id         category sub_category  \
0          42420    South  FUR-BO-10001798        Furniture    Bookcases   
1          42420    South  FUR-CH-10000454        Furniture       Chairs   
5491       77070  Central  OFF-ST-10000615  Office Supplies      Storage   
6877       75217  Central  FUR-FU-10004952        Furniture  Furnishings   
6878       75217  Central  OFF-PA-10003001  Office Supplies        Paper   

                                           product_name    sales  quantity  \
0                     Bush Somerset Collection Bookcase  261.960         2   
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.940         3   
5491  SimpliFile Personal File, Black Granite, 15w x...   18.160         2   
6877  C-Line Cubicle Keepers Polyproplyene Holder w/...  131.376         6   
6878                                         Xerox 1986    5.344         1   

      discount    profit  
0          0.0   41.9136  
1          0.0  219.5820  
5491       0.2    1.8160  
6877       0.6  -95.2476  
6878       0.2    1.8704  

[5 rows x 21 columns]

In [ ]:
df[ df["customer_name"] == "Claire Gute" ][["order_date", "customer_id", "customer_name"]].head()

order_date customer_id customer_name
0     2016-11-08    CG-12520   Claire Gute
1     2016-11-08    CG-12520   Claire Gute
5491  2017-01-26    CG-12520   Claire Gute
6877  2015-10-15    CG-12520   Claire Gute
6878  2015-10-15    CG-12520   Claire Gute

In [ ]:
# query => filter rows with conditions
df.query(" city == 'Los Angeles' ").head()

row_id        order_id  order_date   ship_date       ship_mode customer_id  \
2       3  CA-2016-138688  2016-06-12  2016-06-16    Second Class    DV-13045   
5       6  CA-2014-115812  2014-06-09  2014-06-14  Standard Class    BH-11710   
6       7  CA-2014-115812  2014-06-09  2014-06-14  Standard Class    BH-11710   
7       8  CA-2014-115812  2014-06-09  2014-06-14  Standard Class    BH-11710   
8       9  CA-2014-115812  2014-06-09  2014-06-14  Standard Class    BH-11710   

     customer_name    segment        country         city  ... postal_code  \
2  Darrin Van Huff  Corporate  United States  Los Angeles  ...       90036   
5  Brosina Hoffman   Consumer  United States  Los Angeles  ...       90032   
6  Brosina Hoffman   Consumer  United States  Los Angeles  ...       90032   
7  Brosina Hoffman   Consumer  United States  Los Angeles  ...       90032   
8  Brosina Hoffman   Consumer  United States  Los Angeles  ...       90032   

   region       product_id         category sub_category  \
2    West  OFF-LA-10000240  Office Supplies       Labels   
5    West  FUR-FU-10001487        Furniture  Furnishings   
6    West  OFF-AR-10002833  Office Supplies          Art   
7    West  TEC-PH-10002275       Technology       Phones   
8    West  OFF-BI-10003910  Office Supplies      Binders   

                                        product_name    sales  quantity  \
2  Self-Adhesive Address Labels for Typewriters b...   14.620         2   
5  Eldon Expressions Wood and Plastic Desk Access...   48.860         7   
6                                         Newell 322    7.280         4   
7                     Mitel 5320 IP Phone VoIP phone  907.152         6   
8  DXL Angle-View Binders with Locking Rings by S...   18.504         3   

   discount   profit  
2       0.0   6.8714  
5       0.0  14.1694  
6       0.0   1.9656  
7       0.2  90.7152  
8       0.2   5.7825  

[5 rows x 21 columns]

In [ ]:
# query => filter rows with conditions
df.query(" city == 'Los Angeles' and category == 'Furniture' ").head()

row_id        order_id  order_date   ship_date       ship_mode  \
5         6  CA-2014-115812  2014-06-09  2014-06-14  Standard Class   
10       11  CA-2014-115812  2014-06-09  2014-06-14  Standard Class   
65       66  CA-2015-135545  2015-11-24  2015-11-30  Standard Class   
128     129  US-2016-125969  2016-11-06  2016-11-10    Second Class   
129     130  US-2016-125969  2016-11-06  2016-11-10    Second Class   

    customer_id     customer_name      segment        country         city  \
5      BH-11710   Brosina Hoffman     Consumer  United States  Los Angeles   
10     BH-11710   Brosina Hoffman     Consumer  United States  Los Angeles   
65     KM-16720      Kunst Miller     Consumer  United States  Los Angeles   
128    LS-16975  Lindsay Shagiari  Home Office  United States  Los Angeles   
129    LS-16975  Lindsay Shagiari  Home Office  United States  Los Angeles   

     ... postal_code  region       product_id   category sub_category  \
5    ...       90032    West  FUR-FU-10001487  Furniture  Furnishings   
10   ...       90032    West  FUR-TA-10001539  Furniture       Tables   
65   ...       90004    West  FUR-FU-10000397  Furniture  Furnishings   
128  ...       90004    West  FUR-CH-10001146  Furniture       Chairs   
129  ...       90004    West  FUR-FU-10003773  Furniture  Furnishings   

                                          product_name     sales  quantity  \
5    Eldon Expressions Wood and Plastic Desk Access...    48.860         7   
10            Chromcraft Rectangular Conference Tables  1706.184         9   
65                         Luxo Economy Swing Arm Lamp    79.760         4   
128                           Global Task Chair, Black    81.424         2   
129  Eldon Cleatmat Plus Chair Mats for High Pile C...   238.560         3   

     discount   profit  
5         0.0  14.1694  
10        0.2  85.3092  
65        0.0  22.3328  
128       0.2  -9.1602  
129       0.0  26.2416  

[5 rows x 21 columns]

In [ ]:
# query => filter rows with conditions
df.query(" city == 'Los Angeles' and category == 'Furniture' ")[["customer_name", "segment", "city"]].head()

customer_name      segment         city
5     Brosina Hoffman     Consumer  Los Angeles
10    Brosina Hoffman     Consumer  Los Angeles
65       Kunst Miller     Consumer  Los Angeles
128  Lindsay Shagiari  Home Office  Los Angeles
129  Lindsay Shagiari  Home Office  Los Angeles

In [ ]:
## aggregate data
df.groupby("segment")["sales"].sum()

segment
Consumer       1.161401e+06
Corporate      7.061464e+05
Home Office    4.296531e+05
Name: sales, dtype: float64

In [ ]:
## aggregate data
df.groupby(["segment", "region"])["sales"].sum()

segment      region 
Consumer     Central    252031.4340
             East       350908.1670
             South      195580.9710
             West       362880.7730
Corporate    Central    157995.8128
             East       200409.3470
             South      121885.9325
             West       225855.2745
Home Office  Central     91212.6440
             East       127463.7260
             South       74255.0015
             West       136721.7770
Name: sales, dtype: float64

In [ ]:
## aggregate data
df.groupby(["segment", "region"])[["sales", "profit"]].sum()

sales      profit
segment     region                          
Consumer    Central  252031.4340   8564.0481
            East     350908.1670  41190.9843
            South    195580.9710  26913.5728
            West     362880.7730  57450.6040
Corporate   Central  157995.8128  18703.9020
            East     200409.3470  23622.5789
            South    121885.9325  15215.2232
            West     225855.2745  34437.4299
Home Office Central   91212.6440  12438.4124
            East     127463.7260  26709.2168
            South     74255.0015   4620.6343
            West     136721.7770  16530.4150

In [ ]:
## aggregate data
df.groupby(["segment", "region"])[["sales", "profit"]].agg(['sum', 'mean'])

sales                  profit           
                             sum        mean         sum       mean
segment     region                                                 
Consumer    Central  252031.4340  207.946728   8564.0481   7.066046
            East     350908.1670  238.875539  41190.9843  28.040153
            South    195580.9710  233.390180  26913.5728  32.116435
            West     362880.7730  217.033955  57450.6040  34.360409
Corporate   Central  157995.8128  234.763466  18703.9020  27.791831
            East     200409.3470  228.516929  23622.5789  26.935666
            South    121885.9325  238.992025  15215.2232  29.833771
            West     225855.2745  235.265911  34437.4299  35.872323
Home Office Central   91212.6440  208.248046  12438.4124  28.398202
            East     127463.7260  253.911805  26709.2168  53.205611
            South     74255.0015  272.996329   4620.6343  16.987626
            West     136721.7770  239.442692  16530.4150  28.949939

In [ ]:
## aggregate data
df.groupby(["segment", "region"])[["sales", "profit"]].agg(['sum', 'mean']).reset_index()

segment   region        sales                  profit           
                                  sum        mean         sum       mean
0      Consumer  Central  252031.4340  207.946728   8564.0481   7.066046
1      Consumer     East  350908.1670  238.875539  41190.9843  28.040153
2      Consumer    South  195580.9710  233.390180  26913.5728  32.116435
3      Consumer     West  362880.7730  217.033955  57450.6040  34.360409
4     Corporate  Central  157995.8128  234.763466  18703.9020  27.791831
5     Corporate     East  200409.3470  228.516929  23622.5789  26.935666
6     Corporate    South  121885.9325  238.992025  15215.2232  29.833771
7     Corporate     West  225855.2745  235.265911  34437.4299  35.872323
8   Home Office  Central   91212.6440  208.248046  12438.4124  28.398202
9   Home Office     East  127463.7260  253.911805  26709.2168  53.205611
10  Home Office    South   74255.0015  272.996329   4620.6343  16.987626
11  Home Office     West  136721.7770  239.442692  16530.4150  28.949939

In [ ]:
## aggregate data
df.groupby(["segment", "region"])[["sales", "profit"]].agg(['sum', 'mean', 'count']).reset_index()

segment   region        sales                        profit  \
                                  sum        mean count         sum   
0      Consumer  Central  252031.4340  207.946728  1212   8564.0481   
1      Consumer     East  350908.1670  238.875539  1469  41190.9843   
2      Consumer    South  195580.9710  233.390180   838  26913.5728   
3      Consumer     West  362880.7730  217.033955  1672  57450.6040   
4     Corporate  Central  157995.8128  234.763466   673  18703.9020   
5     Corporate     East  200409.3470  228.516929   877  23622.5789   
6     Corporate    South  121885.9325  238.992025   510  15215.2232   
7     Corporate     West  225855.2745  235.265911   960  34437.4299   
8   Home Office  Central   91212.6440  208.248046   438  12438.4124   
9   Home Office     East  127463.7260  253.911805   502  26709.2168   
10  Home Office    South   74255.0015  272.996329   272   4620.6343   
11  Home Office     West  136721.7770  239.442692   571  16530.4150   

                     
         mean count  
0    7.066046  1212  
1   28.040153  1469  
2   32.116435   838  
3   34.360409  1672  
4   27.791831   673  
5   26.935666   877  
6   29.833771   510  
7   35.872323   960  
8   28.398202   438  
9   53.205611   502  
10  16.987626   272  
11  28.949939   571

In [ ]:
## aggregate data
res = df.groupby(["segment", "region"])[["sales", "profit"]] \
        .agg(['sum', 'mean', 'count']) \
        .reset_index()
print(res)

res.to_csv("agg_data.csv")

        segment   region        sales                        profit  \
                                  sum        mean count         sum   
0      Consumer  Central  252031.4340  207.946728  1212   8564.0481   
1      Consumer     East  350908.1670  238.875539  1469  41190.9843   
2      Consumer    South  195580.9710  233.390180   838  26913.5728   
3      Consumer     West  362880.7730  217.033955  1672  57450.6040   
4     Corporate  Central  157995.8128  234.763466   673  18703.9020   
5     Corporate     East  200409.3470  228.516929   877  23622.5789   
6     Corporate    South  121885.9325  238.992025   510  15215.2232   
7     Corporate     West  225855.2745  235.265911   960  34437.4299   
8   Home Office  Central   91212.6440  208.248046   438  12438.4124   
9   Home Office     East  127463.7260  253.911805   502  26709.2168   
10  Home Office    South   74255.0015  272.996329   272   4620.6343   
11  Home Office     West  136721.7770  239.442692   571  16530.4150   

     

In [ ]:
## aggregate data
res = df.query(" region == 'West' ") \
		.groupby(["segment", "region"])[["sales", "profit"]] \
        .agg(['sum', 'mean', 'count']) \
        .reset_index()
res

segment region        sales                        profit             \
                               sum        mean count         sum       mean   
0     Consumer   West  362880.7730  217.033955  1672  57450.6040  34.360409   
1    Corporate   West  225855.2745  235.265911   960  34437.4299  35.872323   
2  Home Office   West  136721.7770  239.442692   571  16530.4150  28.949939   

         
  count  
0  1672  
1   960  
2   571