In [ ]:
print("Hello world")

[1] "Hello world"


In [ ]:
print("I am learning R programming")

[1] "I am learning R programming"


In [ ]:
1

[1] 1

# **Programming Foundation**
- variable
- data type
- data structure
- function
- control flow

In [ ]:
1+1

[1] 2

In [ ]:
5-2

[1] 3

In [ ]:
5*2

[1] 10

In [ ]:
7/2

[1] 3.5

In [ ]:
5**2 # 5*5

[1] 25

In [ ]:
# comment
# note to this code cell
print("hello world")

[1] "hello world"


In [ ]:
print('hello world')

[1] "hello world"


In [ ]:
1+2

[1] 3

## **Variables**

In [ ]:
income <- 35000
expense <- 25000

saving <- income - expense

print(saving)

[1] 10000


In [ ]:
# Variable name: Snack case
my_name <- "John Wick"

In [ ]:
my_name

[1] "John Wick"

In [ ]:
"John Beckham" -> my_name

In [ ]:
my_name

[1] "John Beckham"

In [ ]:
# Remove variable
rm(my_name)

In [ ]:
print(my_name)

ERROR: ignored

In [ ]:
# ไม่นิยมเขียนแบบนี้ ใน R
school = "DataRockie"
print(school)

[1] "DataRockie"


In [ ]:
# save income for 10 years, interest rate 5%

income * (1+0.05) ** 20

[1] 92865.42

## **Data Types**
- numeric
- character (text, string)
- logical (TRUE, FALSE)
- date

- factor เป็นตัวพิเศษในภาษา R เท่านั้น* (categorical - stats, special in R)

เป็นภาษาสำหรับนักสถิติ ดังนั้นจึงไม่ระบุ type แบบ int / float

In [ ]:
# numeric
gpa <- 3.41
print(gpa)

[1] 3.41


In [ ]:
age <- 35
print(age)
print(class(age))

[1] 35
[1] "numeric"


In [ ]:
class(1L)

[1] "integer"

In [ ]:
## character
class("hello world")

[1] "character"

In [1]:
## concat many character
paste("hello", "world", "hahaha")

[1] "hello world hahaha"

In [ ]:
print(class(T))
print(class(TRUE))

print(class(F))
print(class(FALSE))

[1] "logical"
[1] "logical"
[1] "logical"
[1] "logical"


In [ ]:
1+1 == 2

[1] TRUE

In [ ]:
5 > 3

[1] TRUE

In [ ]:
5 < 3

[1] FALSE

In [ ]:
# not equal
5 != 5

[1] FALSE

In [ ]:
!TRUE

[1] FALSE

In [ ]:
!FALSE

[1] TRUE

In [ ]:
# negate
!(1+1 == 2)

[1] FALSE

In [ ]:
# R is case sensitive
"hi" == "Hi"

[1] FALSE

In [ ]:
## date
today_date <- "2023-11-11"
print(today_date)
print(class(today_date))

[1] "2023-11-11"
[1] "character"


In [ ]:
## change character date to date type
today_date <- as.Date("2023-11-11")
print(today_date)
print(class(today_date))

[1] "2023-11-11"
[1] "Date"


In [ ]:
## change date type to character date
today_date <- as.character("2023-11-11")
print(today_date)
print(class(today_date))

[1] "2023-11-11"
[1] "character"


In [ ]:
## as.___() change data type
as.integer(TRUE)

[1] 1

In [ ]:
as.integer(FALSE)

[1] 0

In [ ]:
as.numeric("1234")

[1] 1234

In [ ]:
as.character(1234)

[1] "1234"

In [ ]:
## R name come from?
## country of origin

## Ross Ihaka + Robert Gentleman

## vector => similar to Google Sheets Array
# vector เก็บได้แค่ 1 data type
gender <- c("male", "female", "male")
gender <- factor(gender)

In [ ]:
print(gender)
print(class(gender))

[1] male   female male  
Levels: female male
[1] "factor"


In [ ]:
# is.___() check data type
is.factor(gender)

[1] TRUE

In [ ]:
is.character("123")

[1] TRUE

In [ ]:
## factor has two categories
## 1. norminal: male, female
## 2. ordinal: low < medium < high

## **Data Structures**
- vector (single data type)
- matrix (single data type)
- list
- dataframe

In [ ]:
## vector
# c คือ concat เอาตัวเลขมาเรียงต่อกัน
scores <- c(88, 90, 50, 65, 76)

In [ ]:
scores > 80

[1]  TRUE  TRUE FALSE FALSE FALSE

In [ ]:
## vectorization (no need to write loop)
scores + 2

[1] 90 92 52 67 78

In [ ]:
print(sum(scores))
print(mean(scores))
print(min(scores))
print(max(scores))
print(length(scores))

[1] 369
[1] 73.8
[1] 50
[1] 90
[1] 5


In [ ]:
## subset
scores <- c(
    john = 88,
    minnie = 90,
    david = 50,
    marry = 65,
    anna = 76)

In [ ]:
scores

john minnie  david  marry   anna 
    88     90     50     65     76

In [ ]:
## index starts at 1
## by position 1,2,3
## by name "david", "marry"
## by condition
scores[1]

john 
  88

In [ ]:
scores["john"]

john 
  88

In [ ]:
scores[scores > 50]

john minnie  marry   anna 
    88     90     65     76

In [ ]:
## update value in scores
scores[3] <- 60
scores

john minnie  david  marry   anna 
    88     90     60     65     76

In [ ]:
scores[5] <- 86
scores

john minnie  david  marry   anna 
    88     90     60     65     86

In [ ]:
which.max(scores)

minnie 
     2

In [ ]:
which.min(scores)

david 
    3

In [ ]:
which(scores >= 88)

john minnie 
     1      2

In [ ]:
## friends 5 persons
friends <- c("toy", "john", "mary", "david", "lisa")
friends

[1] "toy"   "john"  "mary"  "david" "lisa"

In [ ]:
paste("hi", friends)

[1] "hi toy"   "hi john"  "hi mary"  "hi david" "hi lisa"

In [ ]:
1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
seq(1,100,5)

[1]  1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96

In [ ]:
## matrix => vector 2 dimensions
m1 <- matrix(1:100, ncol=4)
m1

[,1] [,2] [,3] [,4]
 [1,]  1   26   51    76 
 [2,]  2   27   52    77 
 [3,]  3   28   53    78 
 [4,]  4   29   54    79 
 [5,]  5   30   55    80 
 [6,]  6   31   56    81 
 [7,]  7   32   57    82 
 [8,]  8   33   58    83 
 [9,]  9   34   59    84 
[10,] 10   35   60    85 
[11,] 11   36   61    86 
[12,] 12   37   62    87 
[13,] 13   38   63    88 
[14,] 14   39   64    89 
[15,] 15   40   65    90 
[16,] 16   41   66    91 
[17,] 17   42   67    92 
[18,] 18   43   68    93 
[19,] 19   44   69    94 
[20,] 20   45   70    95 
[21,] 21   46   71    96 
[22,] 22   47   72    97 
[23,] 23   48   73    98 
[24,] 24   49   74    99 
[25,] 25   50   75   100

In [ ]:
## matrix => vector 2 dimensions
m1 <- matrix(1:100, nrow=10)
m1

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  1   11   21   31   41   51   61   71   81    91  
 [2,]  2   12   22   32   42   52   62   72   82    92  
 [3,]  3   13   23   33   43   53   63   73   83    93  
 [4,]  4   14   24   34   44   54   64   74   84    94  
 [5,]  5   15   25   35   45   55   65   75   85    95  
 [6,]  6   16   26   36   46   56   66   76   86    96  
 [7,]  7   17   27   37   47   57   67   77   87    97  
 [8,]  8   18   28   38   48   58   68   78   88    98  
 [9,]  9   19   29   39   49   59   69   79   89    99  
[10,] 10   20   30   40   50   60   70   80   90   100

In [ ]:
## matrix => vector 2 dimensions
m1 <- matrix(1:100, nrow=10, byrow=TRUE)
m1

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]   2    4    6    8   10   12   14   16   18   20  
 [2,]  22   24   26   28   30   32   34   36   38   40  
 [3,]  42   44   46   48   50   52   54   56   58   60  
 [4,]  62   64   66   68   70   72   74   76   78   80  
 [5,]  82   84   86   88   90   92   94   96   98  100  
 [6,] 102  104  106  108  110  112  114  116  118  120  
 [7,] 122  124  126  128  130  132  134  136  138  140  
 [8,] 142  144  146  148  150  152  154  156  158  160  
 [9,] 162  164  166  168  170  172  174  176  178  180  
[10,] 182  184  186  188  190  192  194  196  198  200

In [ ]:
## matrix => vector 2 dimensions
m1 <- matrix(1:100, nrow=10, byrow=TRUE)
m1 * 2 # vectorization

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]   2    4    6    8   10   12   14   16   18   20  
 [2,]  22   24   26   28   30   32   34   36   38   40  
 [3,]  42   44   46   48   50   52   54   56   58   60  
 [4,]  62   64   66   68   70   72   74   76   78   80  
 [5,]  82   84   86   88   90   92   94   96   98  100  
 [6,] 102  104  106  108  110  112  114  116  118  120  
 [7,] 122  124  126  128  130  132  134  136  138  140  
 [8,] 142  144  146  148  150  152  154  156  158  160  
 [9,] 162  164  166  168  170  172  174  176  178  180  
[10,] 182  184  186  188  190  192  194  196  198  200

In [ ]:
## matrix multiplication
m1 <- matrix(c(2,4,5,10), ncol=2)

m2 <- matrix(c(1,1,5,2), ncol=2)

m1 * m2

[,1] [,2]
[1,] 2    25  
[2,] 4    20

In [ ]:
# .dot operation
m1 %*% m2

[,1] [,2]
[1,]  7   20  
[2,] 14   40

In [ ]:
# dimension
dim(m1)

[1] 2 2

In [ ]:
## list, dataframe
## list
customer01 <- list(
    name = "toy",
    age = 35,
    city = "Bangkok",
    favorite_films = c("Dark Knight", "The Marvels")
)

In [ ]:
customer01["name"]

$name
[1] "toy"

In [ ]:
customer01[["age"]]

[1] 35

In [ ]:
customer01["favorite_films"]

$favorite_films
[1] "Dark Knight" "The Marvels"

In [ ]:
customer01[["favorite_films"]][2]

[1] "The Marvels"

In [ ]:
customer01[["city"]]

[1] "Bangkok"

In [ ]:
## list, dataframe
## list (key value)
customer02 <- list(
    name = "Jane",
    age = 28,
    city = "Seoul",
    favorite_films = c("About  Time", "Taylor Swift Concert")
)

In [ ]:
list_customers <- list(customer01, customer02)

In [ ]:
list_customers

[[1]]
[[1]]$name
[1] "toy"

[[1]]$age
[1] 35

[[1]]$city
[1] "Bangkok"

[[1]]$favorite_films
[1] "Dark Knight" "The Marvels"


[[2]]
[[2]]$name
[1] "Jane"

[[2]]$age
[1] 28

[[2]]$city
[1] "Seoul"

[[2]]$favorite_films
[1] "About  Time"          "Taylor Swift Concert"

In [ ]:
cust_name <- list_customers[[1]][["name"]]
cust_name

[1] "toy"

In [ ]:
# dataframe
# the most important in data analyst role

# create a new dataframe from scratch

df <- data.frame(
    id = 1:5,
    name = c("toy", "john", "marry", "jane", "anne"),
    age = c(28, 30, 31, 22, 25),
    movie_lover = c(T, T, F, F, T)
)

In [ ]:
df

id name  age movie_lover
1 1  toy   28   TRUE      
2 2  john  30   TRUE      
3 3  marry 31  FALSE      
4 4  jane  22  FALSE      
5 5  anne  25   TRUE

In [ ]:
df[, c("name", "age")]

name  age
1 toy   28 
2 john  30 
3 marry 31 
4 jane  22 
5 anne  25

In [ ]:
df[1:3, c("name", "age")]

name  age
1 toy   28 
2 john  30 
3 marry 31

In [ ]:
df[c(1,3,5), ]

id name  age movie_lover
1 1  toy   28   TRUE      
3 3  marry 31  FALSE      
5 5  anne  25   TRUE

In [ ]:
# ผลลัพธ์ แบบเดียวกัน
df[["movie_lover"]]
df$movie_lover

[1]  TRUE  TRUE FALSE FALSE  TRUE

[1]  TRUE  TRUE FALSE FALSE  TRUE

In [ ]:
df[!df$movie_lover == T, ]

id name  age movie_lover
3 3  marry 31  FALSE      
4 4  jane  22  FALSE

In [ ]:
# by condition
# & = and
# | = or

df[ (df$age < 30) & (!df$movie_lover == T), ]

id name age movie_lover
4 4  jane 22  FALSE

In [ ]:
df[ (df$age < 30) | (!df$movie_lover == T), ]

id name  age movie_lover city  
1 1  toy   28   TRUE       BKK   
3 3  marry 31  FALSE       BKK   
4 4  jane  22  FALSE       LONDON
5 5  anne  25   TRUE       LONDON

In [ ]:
## create city ( a new column )
df$city <- c(rep("BKK", 3), rep("LONDON", 2)) # replicate

In [ ]:
df[df$city == "BKK", ]

id name  age movie_lover city
1 1  toy   28   TRUE       BKK 
2 2  john  30   TRUE       BKK 
3 3  marry 31  FALSE       BKK

In [ ]:
df$random <- 100
df

id name  age movie_lover city   random
1 1  toy   28   TRUE       BKK    100   
2 2  john  30   TRUE       BKK    100   
3 3  marry 31  FALSE       BKK    100   
4 4  jane  22  FALSE       LONDON 100   
5 5  anne  25   TRUE       LONDON 100

In [ ]:
## remove column
df$random <- NULL
df

id name  age movie_lover city  
1 1  toy   28   TRUE       BKK   
2 2  john  30   TRUE       BKK   
3 3  marry 31  FALSE       BKK   
4 4  jane  22  FALSE       LONDON
5 5  anne  25   TRUE       LONDON

In [ ]:
## write csv file
write.csv(df, "movie.csv", row.names=FALSE)

In [ ]:
movie <- read.csv("movie.csv")
movie

id name  age movie_lover city  
1 1  toy   28   TRUE       BKK   
2 2  john  30   TRUE       BKK   
3 3  marry 31  FALSE       BKK   
4 4  jane  22  FALSE       LONDON
5 5  anne  25   TRUE       LONDON

In [ ]:
# structure
str(movie)

'data.frame':	5 obs. of  5 variables:
 $ id         : int  1 2 3 4 5
 $ name       : chr  "toy" "john" "marry" "jane" ...
 $ age        : int  28 30 31 22 25
 $ movie_lover: logi  TRUE TRUE FALSE FALSE TRUE
 $ city       : chr  "BKK" "BKK" "BKK" "LONDON" ...


# **Function**

In [ ]:
sum( 1:10 )

[1] 55

In [ ]:
my_secret_formula <- function(start, end) {
    (start + end) * end / 2
}

In [ ]:
my_secret_formula(1, 100)

[1] 5050

In [ ]:
## greeting()

greeting <- function() {
    print("Hello world!")
}

In [ ]:
greeting

function() {
    print("Hello world!")
}

In [ ]:
# involve function / execute function
greeting()

[1] "Hello world!"


In [ ]:
## greeting()

greeting <- function(name) {
    text = paste("Hi!", name)
    print(text)
}

In [ ]:
greeting(name="toy")

[1] "Hi! toy"


In [ ]:
add_two_num <- function(a, b){
    return(a+b)
}

add_two_num <- function(a, b){
    a+b # return เป็น optional
}

add_two_num <- function(a, b) a+b

In [ ]:
add_two_num(1,2)

[1] 3

In [ ]:
result <- add_two_num(100,2)
result

[1] 102

In [ ]:
greeting <- function(name="John Wick") {
    return(paste("Hi!", name))
}

greeting()

[1] "Hi! John Wick"

In [ ]:
greeting("Attack on Titan")

[1] "Hi! Attack on Titan"

In [ ]:
greeting <- function(name="John Wick", city="London") {
    return(paste("Hi!", name, "Welcome to", city))
}

greeting()

[1] "Hi! John Wick Welcome to London"

In [ ]:
greeting(city="Bangkok", name="Mary")

[1] "Hi! Mary Welcome to Bangkok"

# **function take user input**

In [ ]:
username <- readline("What is your name: ")
password <- as.numeric(readline("Password: "))

What is your name: folk
Password: 123456


In [ ]:
class(username)
class(password)

[1] "character"

[1] "numeric"

In [ ]:
greeting_v2 <- function() {
    user_name = readline("Hi what's your name: ")
    text = paste("Good morning!", user_name)
    return(text)
}

In [ ]:
greeting_v2()

Hi what's your name: Folk


[1] "Good morning! Folk"

# **Control Flow**

Transferable Knowledge

- if
- for loop
- while loop

In [ ]:
## ifelse
## =IF() in google sheets
## ifelse() in R

score <- 88

ifelse(score >= 80, "passed", "failed")

[1] "passed"

In [ ]:
## if-else
score <- 62

if (score >= 80) {
    print("A")
} else if (score >= 70) {
    print("B")
} else if (score >= 60) {
    print("C")
} else if (score >= 50) {
    print("D")
} else {
    print("Failed")
}

[1] "C"


In [ ]:
grading <- function(score) {
    if (score >= 80) {
        print("A")
    } else if (score >= 70) {
        print("B")
    } else if (score >= 60) {
        print("C")
    } else if (score >= 50) {
        print("D")
    } else {
        print("Failed")
    }
}

In [ ]:
grading(100)

[1] "A"


In [ ]:
numbers <- c(10, 20, 25)
numbers * 2

[1] 20 40 50

In [ ]:
for (number in numbers) {
    number * 2
}

In [ ]:
fruits <- c("banana", "apple", "pineapple")
for (fruit in fruits) {
    print(toupper(fruit))
}

[1] "BANANA"
[1] "APPLE"
[1] "PINEAPPLE"


In [ ]:
toupper(fruits)

[1] "BANANA"    "APPLE"     "PINEAPPLE"

In [ ]:
# infinite loop
# while (1 > 0) {
#     print("hi!")
# }
count <- 0
while (1 > 0) {
    print("hi!")
    count = count + 1
    if (count == 5) {
        print("Done!")
        break
    }
}

[1] "hi!"
[1] "hi!"
[1] "hi!"
[1] "hi!"
[1] "hi!"
[1] "Done!"


In [ ]:
count <- 0
while (count > 5) {
    print("hi!")
    count = count + 1
}

In [ ]:
head(mtcars, 11)

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Duster 360        14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4   
Merc 240D         24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230          22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Merc 280          19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4   
Merc 280C         17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4

In [ ]:
for (i in seq_along(mtcars)) {
    print(mean(mtcars[, i]))
}

[1] 20.09062
[1] 6.1875
[1] 230.7219
[1] 146.6875
[1] 3.596563
[1] 3.21725
[1] 17.84875
[1] 0.4375
[1] 0.40625
[1] 3.6875
[1] 2.8125


In [ ]:
apply(mtcars, 2, mean)

mpg        cyl       disp         hp       drat         wt       qsec 
 20.090625   6.187500 230.721875 146.687500   3.596563   3.217250  17.848750 
        vs         am       gear       carb 
  0.437500   0.406250   3.687500   2.812500

## **Summary Basic Programming**
1. variable
2. data type: numeric, character, logical, date, factor
3. data structure: vector, matrix, list, dataframe
4. function
5. control flow: if for while

## **Homework**

1. game() ==> เป่ายิ้งฉุบ
2. chatbot() ==> user สั่งพิซซ่าได้

In [ ]:
game <- function() {
    print("Hello, welcome to the game!")
    username <- readline("What's your name: ")
    print(paste("Ok", username, "Let's play game!"))
    hands <- c("Hammer", "Scissors", "Paper")
    com_hand <- sample(hands, 1))

    if (user_hand == "hammer" & com_hand == "hand") {
        condition???
    }
}